# Generated by Django 2.1.14 on 2020-03-30 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=11, unique=True, verbose_name='手机号')),
                ('userpic', models.CharField(max_length=128, verbose_name='用户头像url路径')),
                ('username', models.CharField(max_length=64, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('status', models.CharField(max_length=4, verbose_name='用户状态')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'verbose_name': '用户表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=4)),
                ('sex', models.CharField(max_length=4)),
                ('qq', models.CharField(max_length=32)),
                ('job', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=128)),
                ('birthday', models.DateTimeField(null=True, verbose_name='出生日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '用户信息表',
                'verbose_name': '用户信息表',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
        ),
    ]
