# Generated by Django 2.1.14 on 2020-04-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default=1, max_length=4, verbose_name='用户状态'),
        ),
    ]
